// <auto-generated />
namespace Trivago.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HopeFullyFinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HopeFullyFinal));
        
        string IMigrationMetadata.Id
        {
            get { return "202205221640144_HopeFullyFinal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
